run_title: ''

training_model:
  kind: defaultS2
  visualize_each_iters: 1000
  concat_mask: true
  store_discr_outputs_for_vis: true
  generatorS2_path: /mnt/bn/xiabinpaint/ICCV-Inpainting/KDSR-inpainting-lightv2/place-ta.pth
  generatorS1_path: /mnt/bn/xiabinpaint/ICCV-Inpainting/KDSR-inpainting-lightv2/place-ta.pth
losses:
  l1:
    weight_missing: 0
    weight_known: 10
  kd:
    loss_weight: 1.0
    temperature: 0.15
  perceptual:
    weight: 0
  adversarial:
    kind: r1
    weight: 10
    gp_coef: 0.001
    mask_as_fake_target: true
    allow_scale_mask: true
  feature_matching:
    weight: 100
  resnet_pl:
    weight: 30
    weights_path: ${env:TORCH_HOME}

defaults:
  - location: docker
  - data: abl-04-256-mh-dist
  - generatorT: DiffIRS1-place2
  - generator: DiffIRS2-place2
  - discriminator: pix2pixhd_nlayer
  - optimizers: default_optimizers
  - visualizer: directory
  - evaluator: default_inpainted
  - trainer: any_gpu_large_ssim_ddp_finalS
  - hydra: overrides