# @package _group_
kind: DiffIRS1
n_encoder_res: 5
inp_channels: 4
out_channels: 3
dim: 52
num_blocks: [1,1,1,9]
num_refinement_blocks: 0
heads: [1,2,4,8]
ffn_expansion_factor: 1.8
bias: False
LayerNorm_type: WithBias
dual_pixel_task: False
